services:
  ragbot:
    build: .
    container_name: ragbot
    expose:
      - "8000"
    environment:
      - ALLOWED_CLIENTS=${ALLOWED_CLIENTS}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./webroot/:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - ragbot
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./webroot:/var/www/html
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 5d & wait $${!}; certbot renew; done'"

volumes:
  certbot-etc:
  certbot-var:
  html:
